server:
  port: 8081
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://task-tracker-db:5432/postgres
    username: postgres
    password: pass!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
