spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: pass!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
